default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER_NAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: 5432

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

staging:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
